# Generated by Django 4.1.7 on 2023-04-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('modulkode', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('menukode', models.CharField(max_length=7)),
                ('menunama', models.CharField(max_length=25)),
                ('menukontroler', models.CharField(max_length=40)),
                ('menuinduk', models.CharField(blank=True, max_length=7, null=True)),
                ('menustatus', models.CharField(max_length=1)),
                ('menulevel', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modul',
            fields=[
                ('modulkode', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('modulnama', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'modul',
                'managed': False,
            },
        ),
    ]
