# Generated by Django 4.1.7 on 2023-04-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mbarang',
            fields=[
                ('barangkode', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('barangnama', models.CharField(max_length=50)),
                ('brgjnskode', models.CharField(max_length=4)),
                ('satuankode', models.CharField(max_length=3)),
                ('pabrikkode', models.CharField(max_length=5)),
                ('baranghrgbppn', models.FloatField()),
                ('baranghrgsppn', models.FloatField()),
                ('barangterakhir', models.FloatField()),
                ('barangstokmin', models.FloatField()),
                ('barangaktif', models.CharField(max_length=1)),
                ('barangstokmaks', models.FloatField()),
                ('barangpoinqty', models.FloatField()),
                ('barangpoinomz', models.FloatField()),
                ('barangdscmember', models.FloatField()),
                ('barangstatbonus', models.CharField(max_length=1)),
                ('barangbarcode', models.CharField(max_length=20)),
                ('baranghrgpokok', models.BigIntegerField()),
                ('baranghrgkhusus', models.BigIntegerField()),
                ('barangjumsat', models.IntegerField()),
                ('barangtglbliakh', models.DateField()),
                ('barangdisc', models.FloatField()),
                ('barangupdate', models.DateTimeField()),
                ('barangstatpoin', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'mbarang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mbrgjns',
            fields=[
                ('brgjnskode', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('brgjnsnama', models.CharField(max_length=40)),
                ('groupkode', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'mbrgjns',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mbrglok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangkode', models.CharField(max_length=6)),
                ('lokasikode', models.CharField(max_length=4)),
                ('brglokket', models.CharField(blank=True, max_length=10, null=True)),
                ('gudangkode', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'mbrglok',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mbrgsat',
            fields=[
                ('barangkode', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('brgsatnourut', models.CharField(max_length=1)),
                ('brgsatbesar', models.CharField(max_length=3)),
                ('brgsatkecil', models.CharField(max_length=3)),
                ('brgsatsatuan', models.CharField(max_length=3)),
                ('brgsathrgbppn', models.FloatField()),
                ('brgsathrgsppn', models.FloatField()),
                ('brgsatqtybrg', models.CharField(max_length=5)),
                ('brgsatbarcode', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'mbrgsat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mbrgsupp',
            fields=[
                ('supplierkode', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('barangkode', models.CharField(max_length=6)),
                ('brgsupphbppn', models.FloatField()),
                ('brgsupphsppn', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mbrgsupp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mgroup',
            fields=[
                ('groupkode', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('groupnama', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'mgroup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mgudang',
            fields=[
                ('gudangkode', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('gudangnama', models.CharField(max_length=30)),
                ('gudangstatus', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'mgudang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mhrgbaru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangkode', models.CharField(max_length=6)),
                ('supplierkode', models.CharField(max_length=4)),
                ('hrgbarutgl', models.DateField()),
                ('hrgbarubppn', models.FloatField()),
                ('hrgbarusppn', models.FloatField()),
            ],
            options={
                'db_table': 'mhrgbaru',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mhrgcus',
            fields=[
                ('barangkode', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('customerkode', models.CharField(max_length=4)),
                ('hrgcusharga', models.FloatField()),
            ],
            options={
                'db_table': 'mhrgcus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mhrgmod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangkode', models.CharField(max_length=6)),
                ('hrgbarutglnota', models.DateField()),
                ('hrgmodnota', models.FloatField()),
                ('hrgmodppn', models.FloatField()),
                ('hrgmodnppn', models.FloatField()),
                ('hrgmodhrg1', models.FloatField()),
                ('hrgmoddsc1', models.FloatField()),
                ('hrgmodndsc1', models.FloatField()),
                ('hrgmodhrg2', models.FloatField()),
                ('hrgmodds2', models.FloatField()),
                ('hrgmodndsc2', models.FloatField()),
                ('hrgmodhrg3', models.FloatField()),
                ('hrgmoddscfak', models.FloatField()),
                ('hrgmodndscfak', models.FloatField()),
                ('hrgmodhrg4', models.FloatField()),
                ('hrgmodblain', models.FloatField()),
                ('hrgmodqty', models.FloatField()),
                ('hrgmodhblain', models.FloatField()),
                ('hrgmodhmastp', models.FloatField()),
            ],
            options={
                'db_table': 'mhrgmod',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mlokasi',
            fields=[
                ('lokasikode', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('lokasinama', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'mlokasi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mpabrik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pabrikkode', models.CharField(max_length=5)),
                ('pabriknama', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'mpabrik',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mrangehrg',
            fields=[
                ('barangkode', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('rangehrgqty', models.BigIntegerField()),
                ('rangehrgpokok', models.FloatField()),
                ('rangehrgjual', models.FloatField()),
                ('rangehrgprofit', models.FloatField()),
                ('rangehrgedit', models.CharField(max_length=1)),
                ('rangehrgtgl', models.DateField()),
            ],
            options={
                'db_table': 'mrangehrg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Msatuan',
            fields=[
                ('satuankode', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('satuannama', models.CharField(max_length=15)),
                ('satuanlama', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'msatuan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Msupplier',
            fields=[
                ('supplierkode', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('suppliernama', models.CharField(max_length=40)),
                ('supplieralamat', models.CharField(max_length=60)),
                ('supplierkota', models.CharField(max_length=30)),
                ('suppliertelp', models.CharField(max_length=20)),
                ('supplierkontak', models.CharField(max_length=20)),
                ('supplierkodeacc', models.CharField(max_length=10)),
                ('supplierstakota', models.CharField(max_length=1)),
                ('suppliernpwp', models.CharField(max_length=20)),
                ('supplierpkp', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'msupplier',
                'managed': False,
            },
        ),
    ]
