# Generated by Django 4.1.7 on 2023-04-14 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mbarang_mbrgjns_mbrglok_mgroup_mgudang_mhrgbaru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mbarang',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mbrgjns',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mbrglok',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mbrgsat',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mbrgsupp',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mgroup',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mgudang',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mhrgbaru',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mhrgcus',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mhrgmod',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mlokasi',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='modul',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mpabrik',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mrangehrg',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='msatuan',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='msupplier',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='muser',
            options={'managed': False},
        ),
    ]
