# Generated by Django 4.1.7 on 2023-04-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muser',
            fields=[
                ('userid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('userlevel', models.CharField(max_length=1)),
                ('statusapk', models.CharField(max_length=1)),
                ('userimage', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'muser',
                'managed': False,
            },
        ),
    ]
